apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: jkpgcity-project
spec:
  selector:
    app: jkpgcity-project
  ports:
    - name: backend
      protocol: TCP
      port: 3000
      targetPort: 3000
