apiVersion: apps/v1
kind: Deployment
metadata:
  name: jkpgcity-project-deployment
  namespace: jkpgcity-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jkpgcity-project
  template:
    metadata:
      labels:
        app: jkpgcity-project
    spec:
      containers:
        - name: jkpgcity-project
          env:
            - name: DB_HOST
              value: "172.17.0.1"
          image: localhost:5000/jkpgcity-project
