apiVersion: v1
kind: Service
metadata:
  name: jkpgcity-project-service
  namespace: jkpgcity-project
spec:
  selector:
    app: jkpgcity-project
  ports:
    - name: frontend
      protocol: TCP
      port: 4000
      targetPort: 4000
